version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
      mcp:
        patterns:
          - "@modelcontextprotocol/*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"