name: Publish to npm

on:
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type check
      run: npm run typecheck
    
    - name: Build
      run: npm run build
    
    - name: Setup test Strapi instance
      run: ./scripts/setup-test-strapi.sh setup
    
    - name: Run all tests
      run: ./scripts/run-tests.sh
    
    - name: Cleanup
      if: always()
      run: ./scripts/setup-test-strapi.sh clean

  publish-npm:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build package
      run: npm run build
    
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create success comment
      uses: actions/github-script@v7
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: release } = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.payload.release.tag_name
          });
          
          await github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: release.id,
            body: release.body + '\n\n---\n\n✅ **Published to npm:** [`@rocket-sensei/strapi-mcp@' + context.payload.release.tag_name.replace('v', '') + '`](https://www.npmjs.com/package/@rocket-sensei/strapi-mcp)'
          });