name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run type check
      run: npm run typecheck
    
    - name: Create test Strapi app
      run: |
        npx create-strapi@latest test-strapi-app \
          --typescript \
          --no-run \
          --no-example \
          --no-git-init \
          --dbclient=sqlite \
          --skip-cloud \
          --install
        
        cd test-strapi-app
        npm install strapi-plugin-init-admin-user
        
        # Configure environment
        cat > .env << EOF
        STRAPI_TELEMETRY_DISABLED=true
        INIT_ADMIN_USERNAME=admin
        INIT_ADMIN_PASSWORD=Admin123!
        INIT_ADMIN_FIRSTNAME=Test
        INIT_ADMIN_LASTNAME=Admin
        INIT_ADMIN_EMAIL=admin@test.com
        ADMIN_JWT_SECRET=$(openssl rand -base64 32)
        API_TOKEN_SALT=$(openssl rand -base64 16)
        APP_KEYS=$(openssl rand -base64 32),$(openssl rand -base64 32)
        TRANSFER_TOKEN_SALT=$(openssl rand -base64 16)
        JWT_SECRET=$(openssl rand -base64 32)
        EOF
        
        npm run build
    
    - name: Start Strapi
      run: |
        cd test-strapi-app
        npm run develop &
        STRAPI_PID=$!
        echo "STRAPI_PID=$STRAPI_PID" >> $GITHUB_ENV
        
        # Wait for Strapi to be ready
        max_attempts=60
        attempt=0
        while [ $attempt -lt $max_attempts ]; do
          if curl -s http://localhost:1337/_health > /dev/null; then
            echo "Strapi is ready!"
            break
          fi
          attempt=$((attempt + 1))
          sleep 2
        done
        
        if [ $attempt -eq $max_attempts ]; then
          echo "Strapi failed to start"
          exit 1
        fi
    
    - name: Run tests
      env:
        STRAPI_URL: http://localhost:1337
        STRAPI_ADMIN_EMAIL: admin@test.com
        STRAPI_ADMIN_PASSWORD: Admin123!
        STRAPI_DEV_MODE: true
      run: npm test
    
    - name: Upload coverage
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
    
    - name: Stop Strapi
      if: always()
      run: |
        if [ -n "$STRAPI_PID" ]; then
          kill $STRAPI_PID || true
        fi